export const PRESETS = {
  "True Zero (Neutral)": {
    scanlineStrength: 0,
    phosphorMask: 0,
    barrelDistortion: 0,
    bloom: 0,
    flicker: 0,
    chromaticAberration: 0,
    noise: 0,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "none",
  },
  "Consumer TV": {
    scanlineStrength: 0.45,
    phosphorMask: 0.5,
    barrelDistortion: -0.03,
    bloom: 0.36,
    flicker: 0.16,
    chromaticAberration: 0.14,
    noise: 0.2,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "phosphor",
  },
  "PVM/BVM": {
    scanlineStrength: 0.32,
    phosphorMask: 0.62,
    barrelDistortion: -0.012,
    bloom: 0.12,
    flicker: 0.08,
    chromaticAberration: 0.04,
    noise: 0.1,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "aperture",
  },
  Arcade: {
    scanlineStrength: 0.42,
    phosphorMask: 0.5,
    barrelDistortion: -0.047,
    bloom: 0.55,
    flicker: 0.2,
    chromaticAberration: 0.2,
    noise: 0.3,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "slot",
  },
  "Late-80s Home VHS": {
    scanlineStrength: 0.52,
    phosphorMask: 0.26,
    barrelDistortion: -0.094,
    bloom: 0.62,
    flicker: 0.16,
    chromaticAberration: 0.51,
    noise: 0.33,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.23,
    advancedTimebaseWobble: 0.34,
    advancedHeadSwitching: 0.42,
    advancedChromaDelay: 0.33,
    advancedCrossColor: 0.38,
    advancedDropouts: 0.31,
    advancedGhosting: 0.29,
    advancedInterlacing: 0.29,
    advancedFrameStutter: 0.22,
    advancedRfInterference: 0.24,
    advancedExposurePump: 0.19,
    advancedWhiteBalanceDrift: 0.21,
    advancedFocusBreathing: 0.18,
    advancedTapeCrease: 0.2,
    advancedTimestampOSD: 0.54,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
  },
  "90s Rental Tape (3rd Gen Dub)": {
    scanlineStrength: 0.59,
    phosphorMask: 0.2,
    barrelDistortion: -0.109,
    bloom: 0.7,
    flicker: 0.2,
    chromaticAberration: 0.62,
    noise: 0.45,
    pixelSize: 3,
    maskScale: 1.2,
    advancedLineJitter: 0.31,
    advancedTimebaseWobble: 0.44,
    advancedHeadSwitching: 0.56,
    advancedChromaDelay: 0.46,
    advancedCrossColor: 0.54,
    advancedDropouts: 0.49,
    advancedGhosting: 0.43,
    advancedInterlacing: 0.38,
    advancedFrameStutter: 0.44,
    advancedRfInterference: 0.34,
    advancedExposurePump: 0.26,
    advancedWhiteBalanceDrift: 0.24,
    advancedFocusBreathing: 0.24,
    advancedTapeCrease: 0.37,
    advancedTimestampOSD: 0.62,
    advancedOSDStyle: 2,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.08,
    advancedGenerationLoss: 0.72,
    advancedMacroBlocking: 0.18,
  },
  "Hi8 Vacation Cam": {
    scanlineStrength: 0.41,
    phosphorMask: 0.32,
    barrelDistortion: -0.058,
    bloom: 0.46,
    flicker: 0.11,
    chromaticAberration: 0.24,
    noise: 0.2,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.09,
    advancedTimebaseWobble: 0.16,
    advancedHeadSwitching: 0.21,
    advancedChromaDelay: 0.24,
    advancedCrossColor: 0.14,
    advancedDropouts: 0.16,
    advancedGhosting: 0.24,
    advancedInterlacing: 0.26,
    advancedFrameStutter: 0.05,
    advancedRfInterference: 0.16,
    advancedExposurePump: 0.23,
    advancedWhiteBalanceDrift: 0.31,
    advancedFocusBreathing: 0.17,
    advancedTapeCrease: 0.12,
    advancedTimestampOSD: 0.38,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
  },
  "MiniDV Family Cam (2002)": {
    scanlineStrength: 0.3,
    phosphorMask: 0.44,
    barrelDistortion: -0.039,
    bloom: 0.32,
    flicker: 0.08,
    chromaticAberration: 0.17,
    noise: 0.19,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.02,
    advancedTimebaseWobble: 0.05,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.12,
    advancedCrossColor: 0.06,
    advancedDropouts: 0.08,
    advancedGhosting: 0.18,
    advancedInterlacing: 0.36,
    advancedFrameStutter: 0.12,
    advancedRfInterference: 0.06,
    advancedExposurePump: 0.28,
    advancedWhiteBalanceDrift: 0.22,
    advancedFocusBreathing: 0.12,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.51,
    advancedOSDStyle: 4,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.12,
    advancedGenerationLoss: 0.05,
    advancedMacroBlocking: 0.08,
  },
  "Off-Air Analog Broadcast": {
    scanlineStrength: 0.45,
    phosphorMask: 0.38,
    barrelDistortion: -0.082,
    bloom: 0.52,
    flicker: 0.14,
    chromaticAberration: 0.37,
    noise: 0.28,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0.2,
    advancedTimebaseWobble: 0.28,
    advancedHeadSwitching: 0.06,
    advancedChromaDelay: 0.24,
    advancedCrossColor: 0.31,
    advancedDropouts: 0.11,
    advancedGhosting: 0.19,
    advancedInterlacing: 0.24,
    advancedFrameStutter: 0.18,
    advancedRfInterference: 0.41,
    advancedExposurePump: 0.21,
    advancedWhiteBalanceDrift: 0.14,
    advancedFocusBreathing: 0.11,
    advancedTapeCrease: 0.03,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
  },
  "Public Access Archive": {
    scanlineStrength: 0.43,
    phosphorMask: 0.34,
    barrelDistortion: -0.07,
    bloom: 0.48,
    flicker: 0.13,
    chromaticAberration: 0.33,
    noise: 0.31,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.15,
    advancedTimebaseWobble: 0.23,
    advancedHeadSwitching: 0.12,
    advancedChromaDelay: 0.28,
    advancedCrossColor: 0.36,
    advancedDropouts: 0.27,
    advancedGhosting: 0.26,
    advancedInterlacing: 0.31,
    advancedFrameStutter: 0.23,
    advancedRfInterference: 0.29,
    advancedExposurePump: 0.25,
    advancedWhiteBalanceDrift: 0.2,
    advancedFocusBreathing: 0.15,
    advancedTapeCrease: 0.11,
    advancedTimestampOSD: 0.68,
    advancedOSDStyle: 7,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "phosphor",
  },
  "Early Web Rip (2006)": {
    scanlineStrength: 0,
    phosphorMask: 0,
    barrelDistortion: 0,
    bloom: 0.04,
    flicker: 0,
    chromaticAberration: 0.02,
    noise: 0.06,
    pixelSize: 4,
    maskScale: 1.3,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.24,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 1,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.46,
    advancedGenerationLoss: 0.18,
    advancedMacroBlocking: 0.34,
    maskType: "none",
  },
  "Security Camera Dump": {
    scanlineStrength: 0,
    phosphorMask: 0,
    barrelDistortion: 0,
    bloom: 0.02,
    flicker: 0,
    chromaticAberration: 0.02,
    noise: 0.2,
    pixelSize: 5,
    maskScale: 1.5,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0.02,
    advancedGhosting: 0.03,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.52,
    advancedRfInterference: 0.19,
    advancedExposurePump: 0.12,
    advancedWhiteBalanceDrift: 0.08,
    advancedFocusBreathing: 0.09,
    advancedTapeCrease: 0.03,
    advancedTimestampOSD: 0.76,
    advancedOSDStyle: 8,
    advancedCctvMonochrome: 1,
    advancedSaturation: 0,
    advancedQuantization: 0.42,
    advancedGenerationLoss: 0.2,
    advancedMacroBlocking: 0.3,
    maskType: "none",
  },
  "Bootleg Concert Cam": {
    scanlineStrength: 0.55,
    phosphorMask: 0.24,
    barrelDistortion: -0.101,
    bloom: 0.76,
    flicker: 0.24,
    chromaticAberration: 0.58,
    noise: 0.52,
    pixelSize: 3,
    maskScale: 1,
    advancedLineJitter: 0.34,
    advancedTimebaseWobble: 0.41,
    advancedHeadSwitching: 0.35,
    advancedChromaDelay: 0.4,
    advancedCrossColor: 0.33,
    advancedDropouts: 0.45,
    advancedGhosting: 0.39,
    advancedInterlacing: 0.33,
    advancedFrameStutter: 0.24,
    advancedRfInterference: 0.37,
    advancedExposurePump: 0.43,
    advancedWhiteBalanceDrift: 0.33,
    advancedFocusBreathing: 0.4,
    advancedTapeCrease: 0.39,
    advancedTimestampOSD: 0.26,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "phosphor",
  },
  "Damaged Archive Recovery": {
    scanlineStrength: 0.49,
    phosphorMask: 0.27,
    barrelDistortion: -0.074,
    bloom: 0.58,
    flicker: 0.18,
    chromaticAberration: 0.46,
    noise: 0.47,
    pixelSize: 3,
    maskScale: 1.1,
    advancedLineJitter: 0.29,
    advancedTimebaseWobble: 0.36,
    advancedHeadSwitching: 0.28,
    advancedChromaDelay: 0.37,
    advancedCrossColor: 0.4,
    advancedDropouts: 0.57,
    advancedGhosting: 0.34,
    advancedInterlacing: 0.3,
    advancedFrameStutter: 0.34,
    advancedRfInterference: 0.46,
    advancedExposurePump: 0.29,
    advancedWhiteBalanceDrift: 0.35,
    advancedFocusBreathing: 0.31,
    advancedTapeCrease: 0.52,
    advancedTimestampOSD: 0.81,
    advancedOSDStyle: 2,
    advancedCctvMonochrome: 0.24,
    advancedQuantization: 0.08,
    advancedGenerationLoss: 0.79,
    advancedMacroBlocking: 0.14,
    maskType: "dot",
  },
  "Retro Pixel LCD": {
    scanlineStrength: 0.08,
    phosphorMask: 0.38,
    barrelDistortion: 0,
    bloom: 0.08,
    flicker: 0.02,
    chromaticAberration: 0.03,
    noise: 0.04,
    pixelSize: 1,
    maskScale: 0.82,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "dot",
  },
  "Cyberpunk OLED": {
    scanlineStrength: 0.14,
    phosphorMask: 0.12,
    barrelDistortion: -0.012,
    bloom: 0.68,
    flicker: 0.03,
    chromaticAberration: 0.06,
    noise: 0.05,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.04,
    advancedInterlacing: 0,
    advancedFrameStutter: 0,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    advancedNeonPhosphorBleed: 0.34,
    // OLED panel = diamond PenTile subpixels, not a CRT aperture grille; vivid neon.
    advancedSaturation: 1.22,
    maskType: "oledPentile",
  },
  "Neon Sign Bloom (TikTok Style)": {
    scanlineStrength: 0.24,
    phosphorMask: 0.74,
    barrelDistortion: -0.002,
    bloom: 1,
    flicker: 0.05,
    chromaticAberration: 0.58,
    noise: 0.08,
    pixelSize: 2,
    maskScale: 0.82,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0.01,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.56,
    advancedCrossColor: 0.62,
    advancedDropouts: 0,
    advancedGhosting: 0.54,
    advancedInterlacing: 0.02,
    advancedFrameStutter: 0,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedSaturation: 1.58,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    advancedFilmGrain: 0,
    advancedFilmDust: 0,
    advancedFilmScratches: 0,
    advancedFilmGateWeave: 0,
    advancedFilmHalation: 0.54,
    advancedNeonPhosphorBleed: 0.92,
    maskType: "dot",
  },
  "Streaming Compression": {
    scanlineStrength: 0.18,
    phosphorMask: 0.22,
    barrelDistortion: 0,
    bloom: 0.2,
    flicker: 0.03,
    chromaticAberration: 0.07,
    noise: 0.12,
    pixelSize: 2,
    maskScale: 1.1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.02,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.12,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.3,
    advancedGenerationLoss: 0.12,
    advancedMacroBlocking: 0.32,
    datamoshDisplacement: 0.14, bitrotCorruption: 0.1,
    maskType: "lowBitrateBlockGrid",
  },
  "Digital Surveillance": {
    scanlineStrength: 0.22,
    phosphorMask: 0.24,
    barrelDistortion: 0,
    bloom: 0.12,
    flicker: 0.02,
    chromaticAberration: 0.04,
    noise: 0.18,
    pixelSize: 3,
    maskScale: 1.2,
    advancedLineJitter: 0.02,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.03,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.26,
    advancedRfInterference: 0.03,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.42,
    advancedOSDStyle: 8,
    advancedCctvMonochrome: 1,
    advancedSaturation: 0,
    advancedQuantization: 0.24,
    advancedGenerationLoss: 0.08,
    advancedMacroBlocking: 0.18,
    maskType: "cmosRollingColumn",
  },
  "Silent Film 1920s": {
    scanlineStrength: 0,
    phosphorMask: 0,
    bloom: 0.08,
    flicker: 0.24,
    chromaticAberration: 0,
    noise: 0.34,
    pixelSize: 2,
    advancedFrameStutter: 0.18,
    advancedExposurePump: 0.22,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedQuantization: 0,
    advancedCctvMonochrome: 1,
    advancedSaturation: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    advancedFilmGrain: 0.68,
    advancedFilmDust: 0.44,
    advancedFilmScratches: 0.62,
    advancedFilmGateWeave: 0.56,
    advancedFilmHalation: 0.22,
    maskType: "none",
  },
  "Technicolor Print 1950s": {
    scanlineStrength: 0.04,
    phosphorMask: 0.08,
    barrelDistortion: -0.01,
    bloom: 0.36,
    flicker: 0.05,
    chromaticAberration: 0.12,
    noise: 0.14,
    pixelSize: 1,
    advancedGhosting: 0.02,
    advancedExposurePump: 0.1,
    advancedWhiteBalanceDrift: 0.08,
    advancedFocusBreathing: 0.04,
    advancedQuantization: 0,
    advancedCctvMonochrome: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    advancedFilmGrain: 0.4,
    advancedFilmDust: 0.14,
    advancedFilmScratches: 0.08,
    advancedFilmGateWeave: 0.2,
    advancedFilmHalation: 0.5,
    // Technicolor's signature: dense subtractive saturation + deep blacks, with
    // 3-strip RGB mis-registration fringing (now via technicolorFringe renderer param).
    advancedSaturation: 1.4,
    imageContrast: 1.14,
    imageBrightness: 0.96,
    technicolorFringe: 0.54,
    maskType: "none",
  },
  "Super 8 Home Reel 1970s": {
    scanlineStrength: 0.06,
    phosphorMask: 0.04,
    barrelDistortion: -0.02,
    bloom: 0.42,
    flicker: 0.18,
    chromaticAberration: 0.18,
    noise: 0.29,
    pixelSize: 2,
    advancedFrameStutter: 0.14,
    advancedExposurePump: 0.34,
    advancedWhiteBalanceDrift: 0.24,
    advancedFocusBreathing: 0.28,
    advancedQuantization: 0,
    advancedCctvMonochrome: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    advancedFilmGrain: 0.76,
    advancedFilmDust: 0.38,
    advancedFilmScratches: 0.28,
    advancedFilmGateWeave: 0.46,
    advancedFilmHalation: 0.4,
    // Super-8 home reels read warm & golden (Kodachrome/Ektachrome) — add a warm
    // cast + gentle saturation/contrast so it isn't a neutral grainy image.
    imageTemperature: 0.2,
    imageTint: 0.05,
    advancedSaturation: 1.14,
    imageContrast: 1.05,
    maskType: "filmSuper8",
  },
  "16mm Broadcast Kinescope": {
    scanlineStrength: 0.22,
    phosphorMask: 0.18,
    barrelDistortion: -0.046,
    bloom: 0.31,
    flicker: 0.08,
    chromaticAberration: 0.11,
    noise: 0.22,
    pixelSize: 2,
    advancedLineJitter: 0.09,
    advancedTimebaseWobble: 0.14,
    advancedGhosting: 0.12,
    advancedInterlacing: 0.2,
    advancedDropouts: 0.08,
    advancedExposurePump: 0.1,
    advancedWhiteBalanceDrift: 0.06,
    advancedFocusBreathing: 0.06,
    advancedQuantization: 0,
    advancedCctvMonochrome: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    advancedFilmGrain: 0.48,
    advancedFilmDust: 0.22,
    advancedFilmScratches: 0.24,
    advancedFilmGateWeave: 0.32,
    advancedFilmHalation: 0.24,
    maskType: "film16mm",
  },
  "Nitrate Newsreel 1930s": {
    scanlineStrength: 0,
    phosphorMask: 0,
    barrelDistortion: 0,
    bloom: 0.18,
    flicker: 0.28,
    chromaticAberration: 0,
    noise: 0.42,
    pixelSize: 3,
    advancedFrameStutter: 0.24,
    advancedExposurePump: 0.34,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0.08,
    advancedQuantization: 0,
    advancedCctvMonochrome: 1,
    advancedSaturation: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    advancedFilmGrain: 0.82,
    advancedFilmDust: 0.54,
    advancedFilmScratches: 0.74,
    advancedFilmGateWeave: 0.63,
    advancedFilmHalation: 0.29,
    // Nitrate decomposition: chemical blotches, edge fogging, mottled damage.
    nitrateDecay: 0.64,
    maskType: "none",
  },
  "Live NTSC Kinescope 1950s": {
    scanlineStrength: 0.17,
    phosphorMask: 0.12,
    barrelDistortion: -0.03,
    bloom: 0.26,
    flicker: 0.11,
    chromaticAberration: 0.05,
    noise: 0.26,
    pixelSize: 2,
    advancedLineJitter: 0.18,
    advancedTimebaseWobble: 0.19,
    advancedGhosting: 0.14,
    advancedInterlacing: 0.32,
    advancedDropouts: 0.07,
    advancedRfInterference: 0.13,
    advancedFrameStutter: 0.16,
    advancedExposurePump: 0.15,
    advancedWhiteBalanceDrift: 0.08,
    advancedFocusBreathing: 0.07,
    advancedFilmGrain: 0.51,
    advancedFilmDust: 0.23,
    advancedFilmScratches: 0.21,
    advancedFilmGateWeave: 0.37,
    advancedFilmHalation: 0.17,
    maskType: "film16mm",
  },
  "U-matic Field Tape 1970s": {
    scanlineStrength: 0.37,
    phosphorMask: 0.28,
    barrelDistortion: -0.061,
    bloom: 0.54,
    flicker: 0.16,
    chromaticAberration: 0.35,
    noise: 0.36,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.27,
    advancedTimebaseWobble: 0.33,
    advancedHeadSwitching: 0.45,
    advancedChromaDelay: 0.36,
    advancedCrossColor: 0.34,
    advancedDropouts: 0.42,
    advancedGhosting: 0.31,
    advancedInterlacing: 0.41,
    advancedFrameStutter: 0.22,
    advancedRfInterference: 0.35,
    advancedExposurePump: 0.23,
    advancedWhiteBalanceDrift: 0.22,
    advancedFocusBreathing: 0.18,
    advancedTapeCrease: 0.29,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0.22,
    advancedMacroBlocking: 0,
    maskType: "phosphor",
  },
  "Betacam SP ENG 1980s": {
    scanlineStrength: 0.3,
    phosphorMask: 0.41,
    barrelDistortion: -0.043,
    bloom: 0.35,
    flicker: 0.09,
    chromaticAberration: 0.15,
    noise: 0.22,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0.11,
    advancedTimebaseWobble: 0.15,
    advancedHeadSwitching: 0.08,
    advancedChromaDelay: 0.16,
    advancedCrossColor: 0.12,
    advancedDropouts: 0.14,
    advancedGhosting: 0.17,
    advancedInterlacing: 0.34,
    advancedFrameStutter: 0.09,
    advancedRfInterference: 0.11,
    advancedExposurePump: 0.18,
    advancedWhiteBalanceDrift: 0.15,
    advancedFocusBreathing: 0.12,
    advancedTapeCrease: 0.06,
    advancedTimestampOSD: 0.18,
    advancedOSDStyle: 7,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.02,
    advancedGenerationLoss: 0.06,
    advancedMacroBlocking: 0,
    maskType: "aperture",
  },
  "LaserDisc Transfer 1990s": {
    scanlineStrength: 0.19,
    phosphorMask: 0.24,
    barrelDistortion: -0.02,
    bloom: 0.22,
    flicker: 0.06,
    chromaticAberration: 0.11,
    noise: 0.16,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0.05,
    advancedTimebaseWobble: 0.08,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.18,
    advancedCrossColor: 0.19,
    advancedDropouts: 0.04,
    advancedGhosting: 0.12,
    advancedInterlacing: 0.22,
    advancedFrameStutter: 0.03,
    advancedRfInterference: 0.1,
    advancedExposurePump: 0.04,
    advancedWhiteBalanceDrift: 0.05,
    advancedFocusBreathing: 0.04,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "dot",
  },
  "DVD Rip 2001": {
    scanlineStrength: 0,
    phosphorMask: 0,
    barrelDistortion: 0,
    bloom: 0.05,
    flicker: 0,
    chromaticAberration: 0.01,
    noise: 0.06,
    pixelSize: 2,
    maskScale: 1.2,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0.18,
    advancedFrameStutter: 0.05,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.24,
    advancedGenerationLoss: 0.04,
    advancedMacroBlocking: 0.19,
    maskType: "none",
  },
  "HDV Camcorder 2005": {
    scanlineStrength: 0.12,
    phosphorMask: 0.2,
    barrelDistortion: -0.012,
    bloom: 0.18,
    flicker: 0.03,
    chromaticAberration: 0.08,
    noise: 0.12,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.01,
    advancedTimebaseWobble: 0.03,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.08,
    advancedCrossColor: 0.03,
    advancedDropouts: 0.02,
    advancedGhosting: 0.07,
    advancedInterlacing: 0.27,
    advancedFrameStutter: 0.08,
    advancedRfInterference: 0.02,
    advancedExposurePump: 0.14,
    advancedWhiteBalanceDrift: 0.11,
    advancedFocusBreathing: 0.09,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.36,
    advancedOSDStyle: 4,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.2,
    advancedGenerationLoss: 0.05,
    advancedMacroBlocking: 0.14,
    maskType: "cmosRollingColumn",
  },
  "DSLR Video 2010": {
    scanlineStrength: 0.03,
    phosphorMask: 0.06,
    barrelDistortion: -0.008,
    bloom: 0.12,
    flicker: 0.02,
    chromaticAberration: 0.07,
    noise: 0.08,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.03,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.02,
    advancedRfInterference: 0,
    advancedExposurePump: 0.18,
    advancedWhiteBalanceDrift: 0.12,
    advancedFocusBreathing: 0.14,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.04,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0.05,
    maskType: "cmosRollingColumn",
  },
  "Early Smartphone 2012": {
    scanlineStrength: 0,
    phosphorMask: 0,
    barrelDistortion: 0,
    bloom: 0.06,
    flicker: 0,
    chromaticAberration: 0.04,
    noise: 0.14,
    pixelSize: 2,
    maskScale: 1.1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.04,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.15,
    advancedRfInterference: 0,
    advancedExposurePump: 0.12,
    advancedWhiteBalanceDrift: 0.17,
    advancedFocusBreathing: 0.08,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.2,
    advancedOSDStyle: 1,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.31,
    advancedGenerationLoss: 0.07,
    advancedMacroBlocking: 0.28,
    maskType: "none",
  },
  "4K HDR Streaming 2020s": {
    scanlineStrength: 0,
    phosphorMask: 0,
    barrelDistortion: 0,
    bloom: 0.16,
    flicker: 0,
    chromaticAberration: 0.01,
    noise: 0.03,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.03,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0.01,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.08,
    advancedGenerationLoss: 0.01,
    advancedMacroBlocking: 0.1,
    maskType: "none",
  },
  "PAL Living Room TV (1970s)": {
    scanlineStrength: 0.48,
    phosphorMask: 0.4,
    barrelDistortion: -0.062,
    bloom: 0.44,
    flicker: 0.09,
    chromaticAberration: 0.22,
    noise: 0.26,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0.12,
    advancedTimebaseWobble: 0.21,
    advancedHeadSwitching: 0.04,
    advancedChromaDelay: 0.29,
    advancedCrossColor: 0.42,
    advancedDropouts: 0.09,
    advancedGhosting: 0.17,
    advancedInterlacing: 0.36,
    advancedFrameStutter: 0.11,
    advancedRfInterference: 0.24,
    advancedExposurePump: 0.16,
    advancedWhiteBalanceDrift: 0.1,
    advancedFocusBreathing: 0.08,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "dot",
  },
  "Video CD Capture (1999)": {
    scanlineStrength: 0.03,
    phosphorMask: 0.18,
    barrelDistortion: 0,
    bloom: 0.07,
    flicker: 0,
    chromaticAberration: 0.03,
    noise: 0.12,
    pixelSize: 3,
    maskScale: 1.3,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.05,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.04,
    advancedInterlacing: 0.14,
    advancedFrameStutter: 0.16,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.39,
    advancedGenerationLoss: 0.17,
    advancedMacroBlocking: 0.36,
    maskType: "lowBitrateBlockGrid",
  },
  "CRT PC Monitor (1995)": {
    scanlineStrength: 0.22,
    phosphorMask: 0.52,
    barrelDistortion: -0.026,
    bloom: 0.18,
    flicker: 0.07,
    chromaticAberration: 0.07,
    noise: 0.09,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.02,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.03,
    advancedInterlacing: 0,
    advancedFrameStutter: 0,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "aperture",
  },
  "Cable Access Recorder (1984)": {
    scanlineStrength: 0.46,
    phosphorMask: 0.29,
    barrelDistortion: -0.086,
    bloom: 0.57,
    flicker: 0.15,
    chromaticAberration: 0.41,
    noise: 0.37,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.24,
    advancedTimebaseWobble: 0.35,
    advancedHeadSwitching: 0.31,
    advancedChromaDelay: 0.39,
    advancedCrossColor: 0.35,
    advancedDropouts: 0.33,
    advancedGhosting: 0.28,
    advancedInterlacing: 0.37,
    advancedFrameStutter: 0.21,
    advancedRfInterference: 0.32,
    advancedExposurePump: 0.22,
    advancedWhiteBalanceDrift: 0.18,
    advancedFocusBreathing: 0.16,
    advancedTapeCrease: 0.24,
    advancedTimestampOSD: 0.47,
    advancedOSDStyle: 7,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0.28,
    advancedMacroBlocking: 0,
    maskType: "phosphor",
  },
  "Early Webcam (2008)": {
    scanlineStrength: 0,
    phosphorMask: 0.22,
    barrelDistortion: 0,
    bloom: 0.05,
    flicker: 0,
    chromaticAberration: 0.03,
    noise: 0.21,
    pixelSize: 3,
    maskScale: 1.25,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.02,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.19,
    advancedRfInterference: 0,
    advancedExposurePump: 0.19,
    advancedWhiteBalanceDrift: 0.28,
    advancedFocusBreathing: 0.11,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.41,
    advancedGenerationLoss: 0.1,
    advancedMacroBlocking: 0.34,
    maskType: "cmosRollingColumn",
  },
  "Polaroid SX-70 Instant": {
    scanlineStrength: 0,
    phosphorMask: 0.24,
    barrelDistortion: -0.018,
    bloom: 0.28,
    flicker: 0.03,
    chromaticAberration: 0.09,
    noise: 0.24,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.05,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.04,
    advancedRfInterference: 0,
    advancedExposurePump: 0.21,
    advancedWhiteBalanceDrift: 0.26,
    advancedFocusBreathing: 0.08,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedSaturation: 1.18,
    advancedQuantization: 0.06,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    advancedFilmGrain: 0.38,
    advancedFilmDust: 0.09,
    advancedFilmScratches: 0.05,
    advancedFilmGateWeave: 0.11,
    advancedFilmHalation: 0.48,
    // SX-70 integral film: green/yellow shadow crossover + warm pinkish highlights.
    imageTemperature: 0.12,
    imageTint: -0.04,
    // SX-70 colour crossover: greenish/yellow shadows, warm highlights (integral dye chemistry).
    polaroidCrossover: 0.68,
    maskType: "instantDyeCloud",
  },
  "Disposable Camera 35mm Flash": {
    scanlineStrength: 0,
    phosphorMask: 0.18,
    barrelDistortion: -0.024,
    bloom: 0.34,
    flicker: 0,
    chromaticAberration: 0.14,
    noise: 0.31,
    pixelSize: 2,
    maskScale: 1.1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.08,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.06,
    advancedRfInterference: 0,
    advancedExposurePump: 0.24,
    advancedWhiteBalanceDrift: 0.31,
    advancedFocusBreathing: 0.12,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedSaturation: 1.24,
    advancedQuantization: 0.14,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    advancedFilmGrain: 0.58,
    advancedFilmDust: 0.16,
    advancedFilmScratches: 0.09,
    advancedFilmGateWeave: 0.14,
    advancedFilmHalation: 0.52,
    maskType: "filmSuper8",
  },
  "Aerochrome Infrared Film": {
    scanlineStrength: 0,
    phosphorMask: 0,
    barrelDistortion: -0.012,
    bloom: 0.27,
    flicker: 0.02,
    chromaticAberration: 0.06,
    noise: 0.18,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0,
    advancedRfInterference: 0,
    advancedExposurePump: 0.12,
    advancedWhiteBalanceDrift: 0.38,
    advancedFocusBreathing: 0.06,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    // Kodak Aerochrome: IR-reflective foliage renders vivid magenta/red. The
    // false-colour remap does the hue work, so saturation stays moderate.
    infraredFalseColor: 0.82,
    advancedSaturation: 1.22,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    advancedFilmGrain: 0.34,
    advancedFilmDust: 0.08,
    advancedFilmScratches: 0.03,
    advancedFilmGateWeave: 0.09,
    advancedFilmHalation: 0.44,
    maskType: "none",
  },
  "Night Vision Camcorder": {
    scanlineStrength: 0,
    phosphorMask: 0.34,
    barrelDistortion: 0,
    bloom: 0.12,
    flicker: 0,
    chromaticAberration: 0.02,
    noise: 0.36,
    pixelSize: 3,
    maskScale: 1.25,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0.04,
    advancedGhosting: 0.06,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.18,
    advancedRfInterference: 0.08,
    advancedExposurePump: 0.35,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0.09,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.48,
    advancedOSDStyle: 8,
    // P43-phosphor / NightShot look: collapse to luma, then map onto the green
    // phosphor ramp. (cctvMonochrome:1 forced pure grayscale before — no green.)
    advancedCctvMonochrome: 0,
    advancedSaturation: 0,
    monochromeTint: "green",
    advancedQuantization: 0.3,
    advancedGenerationLoss: 0.14,
    advancedMacroBlocking: 0.24,
    // IR illuminator central hotspot bloom (near-field overexposure).
    irHotspot: 0.52,
    maskType: "irBloomSpeckle",
  },
  "Police Bodycam 2016": {
    scanlineStrength: 0,
    phosphorMask: 0.22,
    barrelDistortion: -0.075,
    bloom: 0.08,
    flicker: 0,
    chromaticAberration: 0.1,
    noise: 0.19,
    pixelSize: 3,
    maskScale: 1.2,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.02,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.24,
    advancedRfInterference: 0,
    advancedExposurePump: 0.18,
    advancedWhiteBalanceDrift: 0.14,
    advancedFocusBreathing: 0.16,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.64,
    advancedOSDStyle: 5,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.36,
    advancedGenerationLoss: 0.09,
    advancedMacroBlocking: 0.32,
    maskType: "cmosRollingColumn",
  },
  "Covert Spycam Button Lens": {
    scanlineStrength: 0,
    phosphorMask: 0.28,
    barrelDistortion: -0.118,
    bloom: 0.05,
    flicker: 0,
    chromaticAberration: 0.09,
    noise: 0.27,
    pixelSize: 4,
    maskScale: 1.35,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.03,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.31,
    advancedRfInterference: 0,
    advancedExposurePump: 0.19,
    advancedWhiteBalanceDrift: 0.23,
    advancedFocusBreathing: 0.18,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.57,
    advancedOSDStyle: 8,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.46,
    advancedGenerationLoss: 0.13,
    advancedMacroBlocking: 0.41,
    maskType: "lowBitrateBlockGrid",
  },
  "Ring Doorbell Daytime": {
    scanlineStrength: 0,
    phosphorMask: 0.16,
    barrelDistortion: -0.092,
    bloom: 0.06,
    flicker: 0,
    chromaticAberration: 0.06,
    noise: 0.18,
    pixelSize: 3,
    maskScale: 1.2,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.02,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.2,
    advancedRfInterference: 0,
    advancedExposurePump: 0.16,
    advancedWhiteBalanceDrift: 0.11,
    advancedFocusBreathing: 0.07,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.5,
    advancedOSDStyle: 6,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.37,
    advancedGenerationLoss: 0.08,
    advancedMacroBlocking: 0.33,
    maskType: "fisheyeMicrolens",
  },
  "Ring Doorbell Night IR": {
    scanlineStrength: 0,
    phosphorMask: 0.3,
    barrelDistortion: -0.094,
    bloom: 0.1,
    flicker: 0,
    chromaticAberration: 0.02,
    noise: 0.33,
    pixelSize: 4,
    maskScale: 1.25,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0.03,
    advancedGhosting: 0.04,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.29,
    advancedRfInterference: 0,
    advancedExposurePump: 0.28,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0.1,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.68,
    advancedOSDStyle: 6,
    advancedCctvMonochrome: 1,
    advancedSaturation: 0,
    advancedQuantization: 0.44,
    advancedGenerationLoss: 0.12,
    advancedMacroBlocking: 0.36,
    // IR illuminator central hotspot (ring-style narrow-angle illuminator).
    irHotspot: 0.66,
    maskType: "irBloomSpeckle",
  },
  "GoPro Hero3 Action Cam": {
    scanlineStrength: 0,
    phosphorMask: 0.18,
    barrelDistortion: -0.132,
    bloom: 0.14,
    flicker: 0,
    chromaticAberration: 0.11,
    noise: 0.13,
    pixelSize: 2,
    maskScale: 1.1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.03,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.11,
    advancedRfInterference: 0,
    advancedExposurePump: 0.12,
    advancedWhiteBalanceDrift: 0.13,
    advancedFocusBreathing: 0.18,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.18,
    advancedOSDStyle: 5,
    advancedCctvMonochrome: 0,
    advancedSaturation: 1.17,
    advancedQuantization: 0.27,
    advancedGenerationLoss: 0.06,
    advancedMacroBlocking: 0.21,
    maskType: "fisheyeMicrolens",
  },
  "Disposable Security IR Flood": {
    scanlineStrength: 0,
    phosphorMask: 0.36,
    barrelDistortion: 0,
    bloom: 0.07,
    flicker: 0,
    chromaticAberration: 0.01,
    noise: 0.42,
    pixelSize: 5,
    maskScale: 1.35,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0.08,
    advancedGhosting: 0.09,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.38,
    advancedRfInterference: 0.06,
    advancedExposurePump: 0.31,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0.15,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.73,
    advancedOSDStyle: 8,
    advancedCctvMonochrome: 1,
    advancedSaturation: 0,
    advancedQuantization: 0.51,
    advancedGenerationLoss: 0.21,
    advancedMacroBlocking: 0.43,
    // Wide-angle flood IR: strong near-field blow-out (max hotspot strength).
    irHotspot: 0.84,
    maskType: "irBloomSpeckle",
  },
  "ATSC Broadcast Transition (2009)": {
    scanlineStrength: 0.11,
    phosphorMask: 0.14,
    barrelDistortion: -0.008,
    bloom: 0.14,
    flicker: 0.02,
    chromaticAberration: 0.04,
    noise: 0.1,
    pixelSize: 2,
    maskScale: 1.1,
    advancedLineJitter: 0.01,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.03,
    advancedCrossColor: 0,
    advancedDropouts: 0.01,
    advancedGhosting: 0.05,
    advancedInterlacing: 0.09,
    advancedFrameStutter: 0.13,
    advancedRfInterference: 0.03,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0.02,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.27,
    advancedGenerationLoss: 0.04,
    advancedMacroBlocking: 0.22,
    maskType: "lowBitrateBlockGrid",
  },
  "Sony Trinitron WEGA (2001)": {
    scanlineStrength: 0.24,
    phosphorMask: 0.54,
    barrelDistortion: -0.018,
    bloom: 0.22,
    flicker: 0.08,
    chromaticAberration: 0.06,
    noise: 0.1,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.04,
    advancedCrossColor: 0.05,
    advancedDropouts: 0,
    advancedGhosting: 0.05,
    advancedInterlacing: 0.14,
    advancedFrameStutter: 0,
    advancedRfInterference: 0.02,
    advancedExposurePump: 0.02,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "aperture",
  },
  "Shadow Mask CRT Terminal (Amber)": {
    scanlineStrength: 0.36,
    phosphorMask: 0.62,
    barrelDistortion: -0.01,
    bloom: 0.18,
    flicker: 0.04,
    chromaticAberration: 0,
    noise: 0.08,
    pixelSize: 1,
    maskScale: 0.92,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.02,
    advancedInterlacing: 0,
    advancedFrameStutter: 0,
    advancedRfInterference: 0.01,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    // Amber monochrome terminal: collapse to luma then map onto the amber
    // phosphor ramp (cctvMonochrome's fixed sage-green tint read wrong before).
    advancedCctvMonochrome: 0,
    advancedSaturation: 0,
    monochromeTint: "amber",
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "shadowMask",
  },
  "IPS Office LCD (2013)": {
    scanlineStrength: 0.02,
    phosphorMask: 0.2,
    barrelDistortion: 0,
    bloom: 0.04,
    flicker: 0,
    chromaticAberration: 0.01,
    noise: 0.03,
    pixelSize: 1,
    maskScale: 0.9,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "lcdStripeRGB",
  },
  "OLED Smartphone PenTile (2018)": {
    scanlineStrength: 0,
    phosphorMask: 0.24,
    barrelDistortion: 0,
    bloom: 0.12,
    flicker: 0,
    chromaticAberration: 0.01,
    noise: 0.03,
    pixelSize: 1,
    maskScale: 0.86,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.01,
    advancedInterlacing: 0,
    advancedFrameStutter: 0,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedSaturation: 1.08,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "oledPentile",
  },
  "Pioneer Plasma TV (2007)": {
    scanlineStrength: 0.06,
    phosphorMask: 0.34,
    barrelDistortion: 0,
    bloom: 0.32,
    flicker: 0.02,
    chromaticAberration: 0.03,
    noise: 0.09,
    pixelSize: 1,
    maskScale: 1.15,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.04,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.03,
    advancedRfInterference: 0,
    advancedExposurePump: 0.05,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.03,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    maskType: "plasmaCell",
  },
  "2-inch Quadruplex Broadcast (1960s)": {
    scanlineStrength: 0.34,
    phosphorMask: 0.26,
    barrelDistortion: -0.041,
    bloom: 0.38,
    flicker: 0.14,
    chromaticAberration: 0.19,
    noise: 0.27,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.28,
    advancedTimebaseWobble: 0.31,
    advancedHeadSwitching: 0.22,
    advancedChromaDelay: 0.27,
    advancedCrossColor: 0.24,
    advancedDropouts: 0.18,
    advancedGhosting: 0.26,
    advancedInterlacing: 0.44,
    advancedFrameStutter: 0.21,
    advancedRfInterference: 0.29,
    advancedExposurePump: 0.16,
    advancedWhiteBalanceDrift: 0.11,
    advancedFocusBreathing: 0.09,
    advancedTapeCrease: 0.14,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0.18,
    advancedMacroBlocking: 0,
    // Quad's signature "venetian-blind" banding from 4-head segment switching.
    bandingHorizontal: 0.5,
    maskType: "shadowMask",
  },
  "VHS-C Camcorder (1993)": {
    scanlineStrength: 0.5,
    phosphorMask: 0.27,
    barrelDistortion: -0.088,
    bloom: 0.61,
    flicker: 0.17,
    chromaticAberration: 0.47,
    noise: 0.35,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.26,
    advancedTimebaseWobble: 0.37,
    advancedHeadSwitching: 0.49,
    advancedChromaDelay: 0.35,
    advancedCrossColor: 0.43,
    advancedDropouts: 0.34,
    advancedGhosting: 0.32,
    advancedInterlacing: 0.35,
    advancedFrameStutter: 0.18,
    advancedRfInterference: 0.28,
    advancedExposurePump: 0.31,
    advancedWhiteBalanceDrift: 0.29,
    advancedFocusBreathing: 0.26,
    advancedTapeCrease: 0.23,
    advancedTimestampOSD: 0.58,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0.09,
    advancedMacroBlocking: 0,
    maskType: "phosphor",
  },
  "S-VHS Master Tape (1996)": {
    scanlineStrength: 0.36,
    phosphorMask: 0.42,
    barrelDistortion: -0.046,
    bloom: 0.33,
    flicker: 0.09,
    chromaticAberration: 0.16,
    noise: 0.19,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0.12,
    advancedTimebaseWobble: 0.16,
    advancedHeadSwitching: 0.14,
    advancedChromaDelay: 0.15,
    advancedCrossColor: 0.13,
    advancedDropouts: 0.1,
    advancedGhosting: 0.16,
    advancedInterlacing: 0.3,
    advancedFrameStutter: 0.07,
    advancedRfInterference: 0.1,
    advancedExposurePump: 0.12,
    advancedWhiteBalanceDrift: 0.09,
    advancedFocusBreathing: 0.07,
    advancedTapeCrease: 0.05,
    advancedTimestampOSD: 0.14,
    advancedOSDStyle: 7,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0.03,
    advancedMacroBlocking: 0,
    maskType: "aperture",
  },
  "RealPlayer 240p Stream (1999)": {
    scanlineStrength: 0,
    phosphorMask: 0.14,
    barrelDistortion: 0,
    bloom: 0.04,
    flicker: 0,
    chromaticAberration: 0.03,
    noise: 0.17,
    pixelSize: 5,
    maskScale: 1.35,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.03,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.34,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.62,
    advancedGenerationLoss: 0.28,
    advancedMacroBlocking: 0.57,
    maskType: "lowBitrateBlockGrid",
  },
  "Pocket Digicam MJPEG (2004)": {
    scanlineStrength: 0,
    phosphorMask: 0.18,
    barrelDistortion: -0.026,
    bloom: 0.09,
    flicker: 0,
    chromaticAberration: 0.06,
    noise: 0.2,
    pixelSize: 3,
    maskScale: 1.2,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.04,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.16,
    advancedRfInterference: 0,
    advancedExposurePump: 0.17,
    advancedWhiteBalanceDrift: 0.18,
    advancedFocusBreathing: 0.12,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.33,
    advancedOSDStyle: 1,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.34,
    advancedGenerationLoss: 0.1,
    advancedMacroBlocking: 0.29,
    maskType: "cmosRollingColumn",
  },
  "Blu-ray Disc Transfer (2008)": {
    scanlineStrength: 0,
    phosphorMask: 0.04,
    barrelDistortion: 0,
    bloom: 0.11,
    flicker: 0,
    chromaticAberration: 0.01,
    noise: 0.03,
    pixelSize: 1,
    maskScale: 1,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.02,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.06,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0.05,
    maskType: "none",
  },
  "Vine Reupload Compilation (2014)": {
    scanlineStrength: 0,
    phosphorMask: 0.12,
    barrelDistortion: 0,
    bloom: 0.07,
    flicker: 0,
    chromaticAberration: 0.05,
    noise: 0.15,
    pixelSize: 3,
    maskScale: 1.25,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.03,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.27,
    advancedRfInterference: 0,
    advancedExposurePump: 0.08,
    advancedWhiteBalanceDrift: 0.09,
    advancedFocusBreathing: 0.04,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.52,
    advancedGenerationLoss: 0.31,
    advancedMacroBlocking: 0.49,
    datamoshBloom: 0.18, bitrotCorruption: 0.16,
    maskType: "lowBitrateBlockGrid",
  },
  "Vertical Livestream Story (2024)": {
    scanlineStrength: 0,
    phosphorMask: 0.08,
    barrelDistortion: -0.028,
    bloom: 0.13,
    flicker: 0,
    chromaticAberration: 0.03,
    noise: 0.09,
    pixelSize: 2,
    maskScale: 1.05,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.02,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.09,
    advancedRfInterference: 0,
    advancedExposurePump: 0.11,
    advancedWhiteBalanceDrift: 0.07,
    advancedFocusBreathing: 0.06,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.22,
    advancedOSDStyle: 6,
    advancedCctvMonochrome: 0,
    advancedSaturation: 1.12,
    advancedQuantization: 0.22,
    advancedGenerationLoss: 0.07,
    advancedMacroBlocking: 0.24,
    maskType: "oledPentile",
  },
  "Betamax Home Recording (1981)": {
    scanlineStrength: 0.42,
    phosphorMask: 0.31,
    barrelDistortion: -0.071,
    bloom: 0.49,
    flicker: 0.14,
    chromaticAberration: 0.32,
    noise: 0.3,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.21,
    advancedTimebaseWobble: 0.28,
    advancedHeadSwitching: 0.34,
    advancedChromaDelay: 0.29,
    advancedCrossColor: 0.27,
    advancedDropouts: 0.22,
    advancedGhosting: 0.24,
    advancedInterlacing: 0.31,
    advancedFrameStutter: 0.14,
    advancedRfInterference: 0.23,
    advancedExposurePump: 0.17,
    advancedWhiteBalanceDrift: 0.16,
    advancedFocusBreathing: 0.13,
    advancedTapeCrease: 0.15,
    advancedTimestampOSD: 0.21,
    advancedOSDStyle: 7,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0.12,
    advancedMacroBlocking: 0,
    maskType: "phosphor",
  },
  "Video8 Handycam (1988)": {
    scanlineStrength: 0.44,
    phosphorMask: 0.29,
    barrelDistortion: -0.064,
    bloom: 0.52,
    flicker: 0.13,
    chromaticAberration: 0.29,
    noise: 0.27,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.16,
    advancedTimebaseWobble: 0.24,
    advancedHeadSwitching: 0.31,
    advancedChromaDelay: 0.25,
    advancedCrossColor: 0.2,
    advancedDropouts: 0.19,
    advancedGhosting: 0.22,
    advancedInterlacing: 0.28,
    advancedFrameStutter: 0.1,
    advancedRfInterference: 0.2,
    advancedExposurePump: 0.26,
    advancedWhiteBalanceDrift: 0.28,
    advancedFocusBreathing: 0.2,
    advancedTapeCrease: 0.12,
    advancedTimestampOSD: 0.46,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0.06,
    advancedMacroBlocking: 0,
    maskType: "phosphor",
  },
  "MiniDV LP Mode (Dropout-Prone)": {
    scanlineStrength: 0.26,
    phosphorMask: 0.34,
    barrelDistortion: -0.03,
    bloom: 0.25,
    flicker: 0.06,
    chromaticAberration: 0.13,
    noise: 0.18,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.03,
    advancedTimebaseWobble: 0.06,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.1,
    advancedCrossColor: 0.04,
    // DV dropouts are SHARP rectangular block/frozen-macroblock errors, not
    // analog horizontal streaks. Set analog dropouts to near-zero and drive
    // the DV-specific block concealment error instead.
    advancedDropouts: 0.02,
    dvBlockError: 0.52,
    advancedGhosting: 0.14,
    advancedInterlacing: 0.34,
    advancedFrameStutter: 0.21,
    advancedRfInterference: 0.05,
    advancedExposurePump: 0.19,
    advancedWhiteBalanceDrift: 0.18,
    advancedFocusBreathing: 0.1,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.49,
    advancedOSDStyle: 4,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.2,
    advancedGenerationLoss: 0.09,
    advancedMacroBlocking: 0.18,
    maskType: "cmosRollingColumn",
  },
  "D-VHS HD Recording (2003)": {
    scanlineStrength: 0.08,
    phosphorMask: 0.16,
    barrelDistortion: -0.009,
    bloom: 0.15,
    flicker: 0.03,
    chromaticAberration: 0.05,
    noise: 0.1,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.01,
    advancedTimebaseWobble: 0.02,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.04,
    advancedCrossColor: 0.02,
    advancedDropouts: 0.04,
    advancedGhosting: 0.05,
    advancedInterlacing: 0.16,
    advancedFrameStutter: 0.08,
    advancedRfInterference: 0.02,
    advancedExposurePump: 0.06,
    advancedWhiteBalanceDrift: 0.05,
    advancedFocusBreathing: 0.04,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.12,
    advancedOSDStyle: 4,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.17,
    advancedGenerationLoss: 0.03,
    advancedMacroBlocking: 0.12,
    maskType: "aperture",
  },
  "TV Tuner Card Capture (2007)": {
    scanlineStrength: 0.21,
    phosphorMask: 0.22,
    barrelDistortion: 0,
    bloom: 0.14,
    flicker: 0.04,
    chromaticAberration: 0.07,
    noise: 0.17,
    pixelSize: 2,
    maskScale: 1.15,
    advancedLineJitter: 0.04,
    advancedTimebaseWobble: 0.07,
    advancedHeadSwitching: 0.03,
    advancedChromaDelay: 0.11,
    advancedCrossColor: 0.09,
    advancedDropouts: 0.06,
    advancedGhosting: 0.11,
    advancedInterlacing: 0.31,
    advancedFrameStutter: 0.14,
    advancedRfInterference: 0.09,
    advancedExposurePump: 0.05,
    advancedWhiteBalanceDrift: 0.04,
    advancedFocusBreathing: 0.03,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.29,
    advancedGenerationLoss: 0.12,
    advancedMacroBlocking: 0.27,
    maskType: "lowBitrateBlockGrid",
  },
  "XviD AVI Fansub (2003)": {
    scanlineStrength: 0,
    phosphorMask: 0.12,
    barrelDistortion: 0,
    bloom: 0.04,
    flicker: 0,
    chromaticAberration: 0.02,
    noise: 0.08,
    pixelSize: 3,
    maskScale: 1.25,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.11,
    advancedRfInterference: 0,
    advancedExposurePump: 0,
    advancedWhiteBalanceDrift: 0,
    advancedFocusBreathing: 0,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.47,
    advancedGenerationLoss: 0.19,
    advancedMacroBlocking: 0.44,
    bitrotCorruption: 0.28, datamoshDisplacement: 0.22,
    maskType: "lowBitrateBlockGrid",
  },
  "Analog Cable Scrambled Signal": {
    scanlineStrength: 0.53,
    phosphorMask: 0.33,
    barrelDistortion: -0.078,
    bloom: 0.47,
    flicker: 0.19,
    chromaticAberration: 0.41,
    noise: 0.39,
    pixelSize: 2,
    maskScale: 1,
    advancedLineJitter: 0.3,
    advancedTimebaseWobble: 0.33,
    advancedHeadSwitching: 0.08,
    advancedChromaDelay: 0.31,
    advancedCrossColor: 0.45,
    advancedDropouts: 0.17,
    advancedGhosting: 0.24,
    advancedInterlacing: 0.27,
    advancedFrameStutter: 0.29,
    advancedRfInterference: 0.58,
    advancedExposurePump: 0.19,
    advancedWhiteBalanceDrift: 0.12,
    advancedFocusBreathing: 0.1,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    // Sync-suppression scrambling: horizontal tearing, rolling and luma inversion.
    syncSuppression: 0.78,
    maskType: "dot",
  },
  "Rear-Projection CRT TV (2004)": {
    scanlineStrength: 0.19,
    phosphorMask: 0.3,
    barrelDistortion: -0.036,
    bloom: 0.41,
    flicker: 0.06,
    chromaticAberration: 0.21,
    noise: 0.12,
    pixelSize: 1,
    maskScale: 1.08,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.09,
    advancedCrossColor: 0.08,
    advancedDropouts: 0,
    advancedGhosting: 0.26,
    advancedInterlacing: 0.12,
    advancedFrameStutter: 0,
    advancedRfInterference: 0.03,
    advancedExposurePump: 0.04,
    advancedWhiteBalanceDrift: 0.03,
    advancedFocusBreathing: 0.06,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0,
    advancedGenerationLoss: 0,
    advancedMacroBlocking: 0,
    // RPTV projection optics blur the phosphor structure away — no crisp grille,
    // just soft scanlines, bloom and convergence error. "none" keeps the soft bleed.
    maskType: "none",
  },
  "LED Billboard Phone Capture": {
    scanlineStrength: 0,
    phosphorMask: 0.28,
    barrelDistortion: -0.018,
    bloom: 0.19,
    flicker: 0.07,
    chromaticAberration: 0.08,
    noise: 0.11,
    pixelSize: 2,
    maskScale: 0.9,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.06,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.03,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.13,
    advancedRfInterference: 0,
    advancedExposurePump: 0.2,
    advancedWhiteBalanceDrift: 0.15,
    advancedFocusBreathing: 0.05,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0,
    advancedOSDStyle: 0,
    advancedCctvMonochrome: 0,
    advancedSaturation: 1.14,
    advancedQuantization: 0.2,
    advancedGenerationLoss: 0.06,
    advancedMacroBlocking: 0.18,
    maskType: "lcdStripeRGB",
  },
  "Zoom Call Recording (2020)": {
    scanlineStrength: 0,
    phosphorMask: 0.09,
    barrelDistortion: 0,
    bloom: 0.06,
    flicker: 0,
    chromaticAberration: 0.02,
    noise: 0.09,
    pixelSize: 2,
    maskScale: 1.15,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0,
    advancedInterlacing: 0,
    advancedFrameStutter: 0.23,
    advancedRfInterference: 0,
    advancedExposurePump: 0.07,
    advancedWhiteBalanceDrift: 0.08,
    advancedFocusBreathing: 0.03,
    advancedTapeCrease: 0,
    advancedTimestampOSD: 0.37,
    advancedOSDStyle: 6,
    advancedCctvMonochrome: 0,
    advancedQuantization: 0.34,
    advancedGenerationLoss: 0.14,
    advancedMacroBlocking: 0.31,
    maskType: "lowBitrateBlockGrid",
  },

  // ===== Effects Engine v2 Presets =====

  "PAL UHF Antenna (1978)": {
    schemaVersion: 2,
    scanlineStrength: 0.46, phosphorMask: 0.38, barrelDistortion: -0.058, bloom: 0.42,
    flicker: 0.12, chromaticAberration: 0.28, noise: 0.34, pixelSize: 1,
    advancedLineJitter: 0.18, advancedTimebaseWobble: 0.24, advancedRfInterference: 0.38,
    advancedGhosting: 0.22, advancedInterlacing: 0.36,
    lumaNoise: 0.32, chromaNoise: 0.44, chromaPhaseError: 0.28,
    chromaBleedHorizontal: 0.31, blackLevelCrush: 0.18,
    flickerFrequencyHz: 0.42, flickerDepth: 0.22,
    phosphorPersistence: 0.18, beamSpotSizeX: 0.22, beamSpotSizeY: 0.28,
    // Simple-PAL receiver with no delay line on a weak signal → Hanover bars.
    hanoverBars: 0.4,
    maskType: "shadowMask",
  },
  "VHS Mold Damage (30yr Attic)": {
    schemaVersion: 2,
    scanlineStrength: 0.54, phosphorMask: 0.24, barrelDistortion: -0.092, bloom: 0.58,
    flicker: 0.18, chromaticAberration: 0.52, noise: 0.48, pixelSize: 3,
    advancedHeadSwitching: 0.56, advancedDropouts: 0.62, advancedTapeCrease: 0.58,
    advancedChromaDelay: 0.44, advancedTimebaseWobble: 0.48,
    headClogEvents: 0.54, trackingError: 0.62, tapeSkew: 0.38, chromaNoiseStreaking: 0.72,
    lumaNoise: 0.44, chromaNoise: 0.58,
    mediaAgeYears: 30, storageCondition: "moldRisk", copyGenerationCount: 3,
    dropoutFrequency: 0.56, dropoutLength: 0.42,
    maskType: "phosphor",
  },
  "Betamax Humid Garage (1983)": {
    schemaVersion: 2,
    scanlineStrength: 0.44, phosphorMask: 0.3, barrelDistortion: -0.068, bloom: 0.5,
    flicker: 0.14, chromaticAberration: 0.36, noise: 0.38, pixelSize: 2,
    advancedHeadSwitching: 0.38, advancedDropouts: 0.34,
    headClogEvents: 0.28, trackingError: 0.42, tapeSkew: 0.22,
    chromaNoiseStreaking: 0.48, lumaNoise: 0.32, chromaNoise: 0.46,
    mediaAgeYears: 40, storageCondition: "humid", copyGenerationCount: 2,
    wowFlutterSlow: 0.34, wowFlutterFast: 0.18,
    maskType: "phosphor",
  },
  "35mm Faded Cinema Print": {
    schemaVersion: 2,
    scanlineStrength: 0, phosphorMask: 0, bloom: 0.32, flicker: 0.08,
    chromaticAberration: 0.08, noise: 0.22, pixelSize: 1,
    advancedFilmGrain: 0.62, advancedFilmDust: 0.34, advancedFilmScratches: 0.42,
    advancedFilmGateWeave: 0.28, advancedFilmHalation: 0.48,
    grainSize: 0.44, grainChromaticity: 0.52,
    gateJitterX: 0.14, gateJitterY: 0.18, gateRotation: 0.08,
    shutterJudder: 0.22,
    // Cyan dye fades fastest → strong MAGENTA/PINK cast (pushed from 0.62 → 0.82).
    printFadeCyan: 0.82, printFadeMagenta: 0.52, printFadeYellow: 0.78,
    cueMarks: 0.38, spliceFlash: 0.24,
    mediaAgeYears: 50, storageCondition: "hot",
    // Stronger pink skew (imageTint now consumed by renderer).
    advancedSaturation: 0.8, imageTemperature: 0.12, imageTint: 0.22,
    maskType: "none",
  },
  "8mm Kodachrome Home Movie": {
    schemaVersion: 2,
    scanlineStrength: 0, phosphorMask: 0, bloom: 0.38, flicker: 0.16,
    chromaticAberration: 0.14, noise: 0.26, pixelSize: 2,
    advancedFilmGrain: 0.72, advancedFilmDust: 0.42, advancedFilmScratches: 0.32,
    advancedFilmGateWeave: 0.44, advancedFilmHalation: 0.36,
    grainSize: 0.58, grainChromaticity: 0.64,
    gateJitterX: 0.32, gateJitterY: 0.38, gateRotation: 0.14,
    shutterJudder: 0.46,
    printFadeCyan: 0.28, printFadeMagenta: 0.14, printFadeYellow: 0.52,
    vignette: 0.38, cornerSharpnessFalloff: 0.32,
    mediaAgeYears: 45, storageCondition: "ideal",
    // Kodachrome = rich, dense saturation + deep blacks + golden warmth.
    // Added blackLevelCrush for the signature punchy shadow depth.
    advancedSaturation: 1.38, imageTemperature: 0.18, imageContrast: 1.12,
    blackLevelCrush: 0.42,
    maskType: "filmSuper8",
  },
  "YouTube 2007 Re-encode": {
    schemaVersion: 2,
    scanlineStrength: 0, phosphorMask: 0, bloom: 0.04, flicker: 0,
    chromaticAberration: 0.02, noise: 0.08, pixelSize: 4,
    advancedFrameStutter: 0.28, advancedQuantization: 0.52,
    advancedGenerationLoss: 0.34, advancedMacroBlocking: 0.48,
    gopLength: 0.72, deblockingStrength: 0.18, ringingStrength: 0.44,
    chromaSubsamplingMode: "420",
    packetLossBurst: 0.12, upscaleSharpenHalos: 0.36,
    copyGenerationCount: 4,
    maskType: "lowBitrateBlockGrid",
  },
  "MPEG-2 Satellite Glitch": {
    schemaVersion: 2,
    scanlineStrength: 0.08, phosphorMask: 0.12, bloom: 0.1, flicker: 0,
    chromaticAberration: 0.04, noise: 0.14, pixelSize: 3,
    advancedQuantization: 0.38, advancedMacroBlocking: 0.56,
    gopLength: 0.84, deblockingStrength: 0.08, ringingStrength: 0.32,
    chromaSubsamplingMode: "420",
    packetLossBurst: 0.48,
    datamoshBloom: 0.34, datamoshDisplacement: 0.52, bitrotCorruption: 0.46,
    advancedFrameStutter: 0.42, advancedInterlacing: 0.24,
    maskType: "lowBitrateBlockGrid",
  },
  "iPhone 3G Vertical Video": {
    schemaVersion: 2,
    scanlineStrength: 0, phosphorMask: 0, bloom: 0.06, flicker: 0,
    chromaticAberration: 0.04, noise: 0.18, pixelSize: 3,
    advancedFrameStutter: 0.22, advancedQuantization: 0.38,
    advancedMacroBlocking: 0.32,
    rollingShutterSkew: 0.34, fixedPatternNoise: 0.18,
    hotPixels: 0.12, lensSmear: 0.08,
    autoExposureHunt: 0.42,
    chromaSubsamplingMode: "420",
    advancedWhiteBalanceDrift: 0.28,
    maskType: "none",
  },
  "Instagram Live 2024": {
    schemaVersion: 2,
    scanlineStrength: 0, phosphorMask: 0.06, bloom: 0.14, flicker: 0,
    chromaticAberration: 0.02, noise: 0.08, pixelSize: 2,
    advancedFrameStutter: 0.12, advancedQuantization: 0.26,
    advancedMacroBlocking: 0.22,
    gopLength: 0.48, chromaSubsamplingMode: "420",
    packetLossBurst: 0.08,
    rollingShutterSkew: 0.12,
    autoExposureHunt: 0.18,
    advancedSaturation: 1.14,
    maskType: "oledPentile",
  },
  "CRT Plasma Burn-In": {
    schemaVersion: 2,
    scanlineStrength: 0.06, phosphorMask: 0.36, barrelDistortion: 0, bloom: 0.34,
    flicker: 0.02, chromaticAberration: 0.03, noise: 0.08, pixelSize: 1,
    phosphorPersistence: 0.72, beamSpotSizeX: 0.34, beamSpotSizeY: 0.38,
    pixelResponseTime: 0.56,
    scanlineProfile: "soft", subpixelLayoutOverride: "RGB",
    advancedGhosting: 0.44,
    // The defining burn-in trait: a faint persistent retained ghost image
    // independent of the live picture (visible as a pale shadow in dark areas).
    burnInGhost: 0.74,
    mediaAgeYears: 12,
    maskType: "plasmaCell",
  },
  "PenTile OLED Sunlight": {
    schemaVersion: 2,
    scanlineStrength: 0, phosphorMask: 0.22, bloom: 0.18, flicker: 0,
    chromaticAberration: 0.01, noise: 0.02, pixelSize: 1,
    scanlineProfile: "off", subpixelLayoutOverride: "PenTile",
    phosphorPersistence: 0.06, pixelResponseTime: 0.04,
    haze: 0.34, flareGhosts: 0.28, vignette: 0.12,
    advancedSaturation: 1.12,
    blackLevelCrush: 0.08, highlightRollOff: 0.14,
    // OLED in sunlight = washed/raised blacks + reduced contrast (consumed grading;
    // the haze/blackLevelCrush v2 fields above are not read by the renderer yet).
    imageBrightness: 1.06, imageContrast: 0.9,
    maskType: "oledPentile",
  },
  "Trinitron Warm Glow": {
    schemaVersion: 2,
    scanlineStrength: 0.28, phosphorMask: 0.56, barrelDistortion: -0.022, bloom: 0.28,
    flicker: 0.06, chromaticAberration: 0.06, noise: 0.08, pixelSize: 1,
    scanlineProfile: "triadAware", subpixelLayoutOverride: "RGB",
    phosphorPersistence: 0.24, beamSpotSizeX: 0.18, beamSpotSizeY: 0.22,
    highlightRollOff: 0.12, gammaCurve: 1.18,
    // "Warm glow" needs an actual warm cast + slightly pushed colour (consumed
    // grading; the v2 highlightRollOff/gammaCurve fields are not read yet).
    imageTemperature: 0.13, advancedSaturation: 1.05,
    maskType: "aperture",
  },
  "Drone Footage Jello": {
    schemaVersion: 2,
    scanlineStrength: 0, phosphorMask: 0, bloom: 0.12, flicker: 0,
    chromaticAberration: 0.06, noise: 0.06, pixelSize: 1,
    rollingShutterSkew: 0.68,
    lensSmear: 0.14, haze: 0.22, vignette: 0.24,
    cornerSharpnessFalloff: 0.38, flareGhosts: 0.16,
    advancedFrameStutter: 0.04,
    chromaSubsamplingMode: "420",
    advancedQuantization: 0.12, advancedMacroBlocking: 0.08,
    maskType: "none",
  },
  "Restored Archive Master": {
    schemaVersion: 2,
    scanlineStrength: 0.12, phosphorMask: 0.14, bloom: 0.16, flicker: 0.04,
    chromaticAberration: 0.06, noise: 0.08, pixelSize: 1,
    advancedFilmGrain: 0.18, advancedFilmDust: 0.06,
    grainSize: 0.14, grainChromaticity: 0.12,
    mediaAgeYears: 60, storageCondition: "ideal",
    restorationPassLevel: 0.72,
    copyGenerationCount: 1,
    printFadeCyan: 0.08, printFadeMagenta: 0.04, printFadeYellow: 0.12,
    maskType: "none",
  },
  "4th Gen VHS Bootleg": {
    schemaVersion: 2,
    scanlineStrength: 0.56, phosphorMask: 0.22, barrelDistortion: -0.1, bloom: 0.68,
    flicker: 0.22, chromaticAberration: 0.58, noise: 0.52, pixelSize: 3,
    advancedHeadSwitching: 0.52, advancedDropouts: 0.48, advancedTapeCrease: 0.44,
    advancedChromaDelay: 0.48, advancedTimebaseWobble: 0.52,
    advancedGenerationLoss: 0.82,
    headClogEvents: 0.32, trackingError: 0.48, tapeSkew: 0.34,
    chromaNoiseStreaking: 0.64,
    lumaNoise: 0.46, chromaNoise: 0.62,
    wowFlutterSlow: 0.42, wowFlutterFast: 0.28,
    mediaAgeYears: 28, storageCondition: "humid", copyGenerationCount: 4,
    maskType: "phosphor",
  },
  "TikTok Screen Record Repost": {
    schemaVersion: 2,
    scanlineStrength: 0, phosphorMask: 0.04, bloom: 0.08, flicker: 0,
    chromaticAberration: 0.02, noise: 0.06, pixelSize: 2,
    advancedFrameStutter: 0.16, advancedQuantization: 0.44,
    advancedGenerationLoss: 0.38, advancedMacroBlocking: 0.36,
    gopLength: 0.56, chromaSubsamplingMode: "420",
    upscaleSharpenHalos: 0.42,
    copyGenerationCount: 3,
    advancedSaturation: 1.08,
    bitrotCorruption: 0.12, datamoshDisplacement: 0.1,
    maskType: "lowBitrateBlockGrid",
  },
  "Datamosh Bloom (I-Frame Removal)": {
    schemaVersion: 2,
    scanlineStrength: 0, phosphorMask: 0.04, barrelDistortion: 0,
    bloom: 0.16, flicker: 0, chromaticAberration: 0.05, noise: 0.06,
    pixelSize: 2, maskScale: 1,
    advancedFrameStutter: 0.18, advancedQuantization: 0.22,
    advancedMacroBlocking: 0.4,
    gopLength: 0.92, deblockingStrength: 0.05, chromaSubsamplingMode: "420",
    datamoshBloom: 0.78, datamoshDisplacement: 0.62, bitrotCorruption: 0.12,
    advancedSaturation: 1.06,
    maskType: "lowBitrateBlockGrid",
  },
  "Corrupted Codec (Bit-Rot)": {
    schemaVersion: 2,
    scanlineStrength: 0, phosphorMask: 0.06, barrelDistortion: 0,
    bloom: 0.06, flicker: 0, chromaticAberration: 0.08, noise: 0.12,
    pixelSize: 3, maskScale: 1.2,
    advancedQuantization: 0.5, advancedMacroBlocking: 0.58,
    advancedFrameStutter: 0.34, advancedInterlacing: 0.12,
    gopLength: 0.7, ringingStrength: 0.34, packetLossBurst: 0.56,
    chromaSubsamplingMode: "411",
    bitrotCorruption: 0.74, datamoshDisplacement: 0.46, datamoshBloom: 0.22,
    maskType: "lowBitrateBlockGrid",
  },
  "Pixel Sort Glitch Art": {
    schemaVersion: 2,
    scanlineStrength: 0, phosphorMask: 0, barrelDistortion: 0,
    bloom: 0.24, flicker: 0, chromaticAberration: 0.16, noise: 0.04,
    pixelSize: 1, maskScale: 1,
    advancedQuantization: 0.12,
    chromaSubsamplingMode: "444",
    pixelSort: 0.82, datamoshDisplacement: 0.3, bitrotCorruption: 0.18,
    advancedSaturation: 1.28, imageContrast: 1.12,
    maskType: "none",
  },
};


/* ============================================================================
 * TWO-AXIS SYSTEM — Capture/Format × Display
 * ----------------------------------------------------------------------------
 * A "final" look is a signal chain: a CAPTURE / RECORDING / TRANSMISSION format
 * (the source media — film stock, VHS, codec, sensor) shown ON a DISPLAY device
 * (CRT, LCD/OLED, billboard, portable TV). The two axes touch disjoint param
 * families so they stack without conflict. The classic ~95 PRESETS above remain
 * available as one-click "Classics".
 * ========================================================================== */

/** Params that describe the DISPLAY device (the screen the media is shown on). */
export const DISPLAY_PARAM_KEYS = [
  "scanlineStrength", "phosphorMask", "maskScale", "maskType",
  "barrelDistortion", "chromaticAberration", "bloom", "flicker", "pixelSize",
  "phosphorPersistence", "beamSpotSizeX", "beamSpotSizeY", "pixelResponseTime",
  "scanlineProfile", "subpixelLayoutOverride",
];

const DISPLAY_KEY_SET = new Set(DISPLAY_PARAM_KEYS);
/** Non-param bookkeeping keys that must never leak into either axis. */
const META_KEYS = new Set(["schemaVersion", "__category"]);

/** Keep only display-axis keys from an arbitrary param object. */
export function pickDisplayKeys(obj) {
  const out = {};
  if (!obj) return out;
  for (const k of DISPLAY_PARAM_KEYS) if (k in obj) out[k] = obj[k];
  return out;
}

/** Keep only capture-axis keys (everything that is not a display key or meta). */
export function pickCaptureKeys(obj) {
  const out = {};
  if (!obj) return out;
  for (const [k, v] of Object.entries(obj)) {
    if (DISPLAY_KEY_SET.has(k) || META_KEYS.has(k)) continue;
    out[k] = v;
  }
  return out;
}

/**
 * Merge a capture preset and a display preset into a single override object.
 * Capture keys come from the capture preset, display keys from the display
 * preset — disjoint sets, so no clobbering. Used by tests and single-intensity
 * callers; the app blends each axis with its own intensity (see Index.applyChain).
 */
export function combineChain(captureValues, displayValues) {
  return { ...pickCaptureKeys(captureValues || {}), ...pickDisplayKeys(displayValues || {}) };
}

/* ---- Neutral pass-throughs ------------------------------------------------ */

/** A perfectly clean modern panel — used when no display is chosen. */
export const NEUTRAL_DISPLAY = {
  scanlineStrength: 0, phosphorMask: 0, maskScale: 1, maskType: "none",
  barrelDistortion: 0, chromaticAberration: 0, bloom: 0.04, flicker: 0, pixelSize: 1,
  phosphorPersistence: 0, beamSpotSizeX: 0, beamSpotSizeY: 0, pixelResponseTime: 0,
  scanlineProfile: "off", subpixelLayoutOverride: "none",
};

/** An untouched digital source — used when no capture format is chosen. */
export const NEUTRAL_CAPTURE = { noise: 0 };

/* ---- DISPLAY DEVICES ------------------------------------------------------ */

export const DISPLAY_PRESETS = {
  "Direct / No Display": { ...NEUTRAL_DISPLAY },

  // CRT family — derived from the matching classics, display-keys only.
  "Consumer CRT TV": pickDisplayKeys(PRESETS["Consumer TV"]),
  "PVM/BVM Monitor": pickDisplayKeys(PRESETS["PVM/BVM"]),
  "Trinitron WEGA": pickDisplayKeys(PRESETS["Sony Trinitron WEGA (2001)"]),
  "Arcade Monitor": pickDisplayKeys(PRESETS["Arcade"]),
  "Shadow-Mask Amber Terminal": pickDisplayKeys(PRESETS["Shadow Mask CRT Terminal (Amber)"]),
  "Rear-Projection CRT": pickDisplayKeys(PRESETS["Rear-Projection CRT TV (2004)"]),
  "PAL Living-Room TV": pickDisplayKeys(PRESETS["PAL Living Room TV (1970s)"]),

  // Flat panels.
  "IPS Office LCD": pickDisplayKeys(PRESETS["IPS Office LCD (2013)"]),
  "OLED PenTile Smartphone": pickDisplayKeys(PRESETS["OLED Smartphone PenTile (2018)"]),
  "Pioneer Plasma": pickDisplayKeys(PRESETS["Pioneer Plasma TV (2007)"]),
  "Cyberpunk OLED": pickDisplayKeys(PRESETS["Cyberpunk OLED"]),
  "E-Paper Display": {
    scanlineStrength: 0, phosphorMask: 0.06, maskScale: 0.9, maskType: "dot",
    barrelDistortion: 0, chromaticAberration: 0, bloom: 0, flicker: 0, pixelSize: 1,
    phosphorPersistence: 0, beamSpotSizeX: 0, beamSpotSizeY: 0,
    pixelResponseTime: 0.62, scanlineProfile: "off", subpixelLayoutOverride: "none",
  },
  "Handheld Pixel LCD (Game Boy)": {
    scanlineStrength: 0.08, phosphorMask: 0.42, maskScale: 0.78, maskType: "dot",
    barrelDistortion: 0, chromaticAberration: 0.02, bloom: 0.04, flicker: 0, pixelSize: 1,
    phosphorPersistence: 0, beamSpotSizeX: 0, beamSpotSizeY: 0,
    pixelResponseTime: 0.4, scanlineProfile: "off", subpixelLayoutOverride: "none",
  },

  // Large / public displays.
  "LED Billboard": {
    scanlineStrength: 0, phosphorMask: 0.82, maskScale: 2, maskType: "dot",
    barrelDistortion: 0, chromaticAberration: 0.04, bloom: 0.52, flicker: 0.04, pixelSize: 2,
    phosphorPersistence: 0, beamSpotSizeX: 0.18, beamSpotSizeY: 0.18,
    pixelResponseTime: 0.12, scanlineProfile: "off", subpixelLayoutOverride: "RGB",
  },
  "Stadium Jumbotron": {
    scanlineStrength: 0.06, phosphorMask: 0.7, maskScale: 1.9, maskType: "dot",
    barrelDistortion: 0, chromaticAberration: 0.08, bloom: 0.66, flicker: 0.06, pixelSize: 2,
    phosphorPersistence: 0.1, beamSpotSizeX: 0.22, beamSpotSizeY: 0.22,
    pixelResponseTime: 0.18, scanlineProfile: "soft", subpixelLayoutOverride: "RGB",
  },
  "Cinema Projector": {
    scanlineStrength: 0, phosphorMask: 0, maskScale: 1, maskType: "none",
    barrelDistortion: 0.006, chromaticAberration: 0.05, bloom: 0.2, flicker: 0.05, pixelSize: 1,
    phosphorPersistence: 0, beamSpotSizeX: 0.08, beamSpotSizeY: 0.08,
    pixelResponseTime: 0, scanlineProfile: "off", subpixelLayoutOverride: "none",
  },
  "IMAX Large-Format Screen": {
    scanlineStrength: 0, phosphorMask: 0, maskScale: 1, maskType: "none",
    barrelDistortion: 0, chromaticAberration: 0.01, bloom: 0.06, flicker: 0, pixelSize: 1,
    phosphorPersistence: 0, beamSpotSizeX: 0, beamSpotSizeY: 0,
    pixelResponseTime: 0, scanlineProfile: "off", subpixelLayoutOverride: "none",
  },

  // Portable / retro.
  "Portable Pocket TV": {
    scanlineStrength: 0.32, phosphorMask: 0.26, maskScale: 1, maskType: "phosphor",
    barrelDistortion: -0.045, chromaticAberration: 0.2, bloom: 0.3, flicker: 0.13, pixelSize: 1,
    phosphorPersistence: 0.18, beamSpotSizeX: 0.2, beamSpotSizeY: 0.16,
    pixelResponseTime: 0.1, scanlineProfile: "soft", subpixelLayoutOverride: "none",
  },
  "CRT Viewfinder": {
    scanlineStrength: 0.5, phosphorMask: 0.32, maskScale: 0.9, maskType: "phosphor",
    barrelDistortion: -0.06, chromaticAberration: 0.1, bloom: 0.34, flicker: 0.16, pixelSize: 2,
    phosphorPersistence: 0.24, beamSpotSizeX: 0.3, beamSpotSizeY: 0.26,
    pixelResponseTime: 0.14, scanlineProfile: "hard", subpixelLayoutOverride: "none",
  },
  "Handheld LCD Screen": {
    scanlineStrength: 0, phosphorMask: 0.12, maskScale: 0.85, maskType: "dot",
    barrelDistortion: 0, chromaticAberration: 0.03, bloom: 0.06, flicker: 0, pixelSize: 1,
    phosphorPersistence: 0, beamSpotSizeX: 0, beamSpotSizeY: 0,
    pixelResponseTime: 0.46, scanlineProfile: "off", subpixelLayoutOverride: "RGB",
  },
};

export const DISPLAY_PRESET_CATEGORIES = {
  "Reference": ["Direct / No Display"],
  "CRT": [
    "Consumer CRT TV", "PVM/BVM Monitor", "Trinitron WEGA", "Arcade Monitor",
    "Shadow-Mask Amber Terminal", "Rear-Projection CRT", "PAL Living-Room TV",
  ],
  "Flat Panel": [
    "IPS Office LCD", "OLED PenTile Smartphone", "Pioneer Plasma", "Cyberpunk OLED",
    "E-Paper Display", "Handheld Pixel LCD (Game Boy)",
  ],
  "Large / Public": [
    "LED Billboard", "Stadium Jumbotron", "Cinema Projector", "IMAX Large-Format Screen",
  ],
  "Portable / Retro": [
    "Portable Pocket TV", "CRT Viewfinder", "Handheld LCD Screen",
  ],
};

/* ---- CAPTURE / RECORDING / TRANSMISSION FORMATS --------------------------- */

export const CAPTURE_PRESETS = {
  "Direct Digital": { ...NEUTRAL_CAPTURE },

  // Film stocks.
  "Silent B&W Film 1920s": pickCaptureKeys(PRESETS["Silent Film 1920s"]),
  "Nitrate Newsreel 1930s": pickCaptureKeys(PRESETS["Nitrate Newsreel 1930s"]),
  "Technicolor Print 1950s": pickCaptureKeys(PRESETS["Technicolor Print 1950s"]),
  "Super 8 Home Reel": pickCaptureKeys(PRESETS["Super 8 Home Reel 1970s"]),
  "16mm Kinescope": pickCaptureKeys(PRESETS["16mm Broadcast Kinescope"]),
  "35mm Faded Print": pickCaptureKeys(PRESETS["35mm Faded Cinema Print"]),
  "8mm Kodachrome": pickCaptureKeys(PRESETS["8mm Kodachrome Home Movie"]),
  "Aerochrome IR Film": pickCaptureKeys(PRESETS["Aerochrome Infrared Film"]),
  "IMAX 70mm Large-Format": {
    advancedFilmGrain: 0.08, grainSize: 0.18, grainChromaticity: 0.05,
    advancedFilmHalation: 0.12, imageContrast: 1.04, advancedSaturation: 1.06,
    noise: 0.02,
  },

  // Magnetic tape.
  "Late-80s VHS": pickCaptureKeys(PRESETS["Late-80s Home VHS"]),
  "3rd-Gen VHS Dub": pickCaptureKeys(PRESETS["90s Rental Tape (3rd Gen Dub)"]),
  "Betamax": pickCaptureKeys(PRESETS["Betamax Home Recording (1981)"]),
  "Hi8 Camcorder": pickCaptureKeys(PRESETS["Hi8 Vacation Cam"]),
  "MiniDV": pickCaptureKeys(PRESETS["MiniDV Family Cam (2002)"]),
  "S-VHS Master": pickCaptureKeys(PRESETS["S-VHS Master Tape (1996)"]),
  "U-matic Field Tape": pickCaptureKeys(PRESETS["U-matic Field Tape 1970s"]),
  "Betacam SP ENG": pickCaptureKeys(PRESETS["Betacam SP ENG 1980s"]),
  "VHS Mold Damage": pickCaptureKeys(PRESETS["VHS Mold Damage (30yr Attic)"]),

  // Broadcast / transmission.
  "Off-Air Analog Broadcast": pickCaptureKeys(PRESETS["Off-Air Analog Broadcast"]),
  "PAL UHF Antenna": pickCaptureKeys(PRESETS["PAL UHF Antenna (1978)"]),
  "Analog Cable Scramble": pickCaptureKeys(PRESETS["Analog Cable Scrambled Signal"]),
  "ATSC Transition": pickCaptureKeys(PRESETS["ATSC Broadcast Transition (2009)"]),
  "MPEG-2 Satellite Glitch": pickCaptureKeys(PRESETS["MPEG-2 Satellite Glitch"]),

  // Digital codecs.
  "DVD Rip": pickCaptureKeys(PRESETS["DVD Rip 2001"]),
  "Video CD": pickCaptureKeys(PRESETS["Video CD Capture (1999)"]),
  "Early Web Rip": pickCaptureKeys(PRESETS["Early Web Rip (2006)"]),
  "Streaming Compression": pickCaptureKeys(PRESETS["Streaming Compression"]),
  "XviD Fansub": pickCaptureKeys(PRESETS["XviD AVI Fansub (2003)"]),
  "RealPlayer 240p": pickCaptureKeys(PRESETS["RealPlayer 240p Stream (1999)"]),
  "YouTube 2007 Re-encode": pickCaptureKeys(PRESETS["YouTube 2007 Re-encode"]),
  "Blu-ray Transfer": pickCaptureKeys(PRESETS["Blu-ray Disc Transfer (2008)"]),

  // Camera / sensor.
  "Disposable 35mm Flash": pickCaptureKeys(PRESETS["Disposable Camera 35mm Flash"]),
  "Polaroid SX-70": pickCaptureKeys(PRESETS["Polaroid SX-70 Instant"]),
  "Early Smartphone": pickCaptureKeys(PRESETS["Early Smartphone 2012"]),
  "DSLR Video": pickCaptureKeys(PRESETS["DSLR Video 2010"]),
  "GoPro Action Cam": pickCaptureKeys(PRESETS["GoPro Hero3 Action Cam"]),
  "Drone (Jello)": pickCaptureKeys(PRESETS["Drone Footage Jello"]),

  // Surveillance.
  "Security Camera": pickCaptureKeys(PRESETS["Security Camera Dump"]),
  "Night Vision IR": pickCaptureKeys(PRESETS["Night Vision Camcorder"]),
  "Police Bodycam": pickCaptureKeys(PRESETS["Police Bodycam 2016"]),
  "Ring Doorbell Night IR": pickCaptureKeys(PRESETS["Ring Doorbell Night IR"]),
  "Covert Spycam": pickCaptureKeys(PRESETS["Covert Spycam Button Lens"]),

  // Social re-encodes.
  "Vine Reupload": pickCaptureKeys(PRESETS["Vine Reupload Compilation (2014)"]),
  "TikTok Screen Record": pickCaptureKeys(PRESETS["TikTok Screen Record Repost"]),
  "Instagram Live": pickCaptureKeys(PRESETS["Instagram Live 2024"]),
  "Vertical Livestream": pickCaptureKeys(PRESETS["Vertical Livestream Story (2024)"]),

  // Glitch / digital decay.
  "Datamosh Bloom": pickCaptureKeys(PRESETS["Datamosh Bloom (I-Frame Removal)"]),
  "Bit-Rot Corruption": pickCaptureKeys(PRESETS["Corrupted Codec (Bit-Rot)"]),
  "Pixel Sort": pickCaptureKeys(PRESETS["Pixel Sort Glitch Art"]),
};

export const CAPTURE_PRESET_CATEGORIES = {
  "Reference": ["Direct Digital"],
  "Film": [
    "Silent B&W Film 1920s", "Nitrate Newsreel 1930s", "Technicolor Print 1950s",
    "Super 8 Home Reel", "16mm Kinescope", "35mm Faded Print", "8mm Kodachrome",
    "Aerochrome IR Film", "IMAX 70mm Large-Format",
  ],
  "Tape": [
    "Late-80s VHS", "3rd-Gen VHS Dub", "Betamax", "Hi8 Camcorder", "MiniDV",
    "S-VHS Master", "U-matic Field Tape", "Betacam SP ENG", "VHS Mold Damage",
  ],
  "Broadcast / Transmission": [
    "Off-Air Analog Broadcast", "PAL UHF Antenna", "Analog Cable Scramble",
    "ATSC Transition", "MPEG-2 Satellite Glitch",
  ],
  "Digital Codec": [
    "DVD Rip", "Video CD", "Early Web Rip", "Streaming Compression", "XviD Fansub",
    "RealPlayer 240p", "YouTube 2007 Re-encode", "Blu-ray Transfer",
  ],
  "Camera / Sensor": [
    "Disposable 35mm Flash", "Polaroid SX-70", "Early Smartphone", "DSLR Video",
    "GoPro Action Cam", "Drone (Jello)",
  ],
  "Surveillance": [
    "Security Camera", "Night Vision IR", "Police Bodycam", "Ring Doorbell Night IR",
    "Covert Spycam",
  ],
  "Social": [
    "Vine Reupload", "TikTok Screen Record", "Instagram Live", "Vertical Livestream",
  ],
  "Glitch / Decay": ["Datamosh Bloom", "Bit-Rot Corruption", "Pixel Sort"],
};




/* ---- SIGNAL-CHAIN AUTO-SUGGESTIONS ---------------------------------------- */
// Pairing intelligence: given one axis, recommend plausible options for the other
// so a chain reads like a believable real-world artifact (e.g. a VHS tape shown
// on a consumer CRT, a TikTok repost on an OLED phone). Built from the period /
// medium affinity between each display family and each capture category.

function buildReverseLookup(catObj) {
  const m = {};
  for (const [cat, names] of Object.entries(catObj)) for (const n of names) m[n] = cat;
  return m;
}

export const CAPTURE_CATEGORY_OF = buildReverseLookup(CAPTURE_PRESET_CATEGORIES);
export const DISPLAY_FAMILY_OF = buildReverseLookup(DISPLAY_PRESET_CATEGORIES);

// Display family -> capture categories that historically/aesthetically belong on it.
const DISPLAY_FAMILY_TO_CAPTURE_CATS = {
  "Reference": ["Digital Codec", "Film", "Camera / Sensor"],
  "CRT": ["Tape", "Broadcast / Transmission", "Camera / Sensor", "Film"],
  "Flat Panel": ["Digital Codec", "Social", "Camera / Sensor", "Glitch / Decay"],
  "Large / Public": ["Social", "Digital Codec", "Broadcast / Transmission", "Film"],
  "Portable / Retro": ["Tape", "Surveillance", "Camera / Sensor", "Broadcast / Transmission"],
};

// Capture category -> display families it was typically watched on.
const CAPTURE_CAT_TO_DISPLAY_FAMILIES = {
  "Reference": ["Flat Panel", "Reference"],
  "Film": ["Large / Public", "CRT"],
  "Tape": ["CRT", "Portable / Retro"],
  "Broadcast / Transmission": ["CRT", "Portable / Retro", "Large / Public"],
  "Digital Codec": ["Flat Panel", "Large / Public"],
  "Camera / Sensor": ["Flat Panel", "CRT", "Portable / Retro"],
  "Surveillance": ["CRT", "Portable / Retro", "Flat Panel"],
  "Social": ["Flat Panel", "Large / Public"],
  "Glitch / Decay": ["Flat Panel", "Large / Public"],
};

/** Recommend capture/format presets that pair well with the given display. */
export function suggestCaptureForDisplay(displayName, limit = 6) {
  const fam = DISPLAY_FAMILY_OF[displayName];
  if (!fam) return [];
  const cats = DISPLAY_FAMILY_TO_CAPTURE_CATS[fam] || [];
  const out = [];
  for (const c of cats) {
    for (const n of CAPTURE_PRESET_CATEGORIES[c] || []) {
      if (n !== "Direct Digital" && !out.includes(n)) out.push(n);
    }
  }
  return out.slice(0, limit);
}

/** Recommend display devices that pair well with the given capture/format. */
export function suggestDisplayForCapture(captureName, limit = 6) {
  const cat = CAPTURE_CATEGORY_OF[captureName];
  if (!cat) return [];
  const fams = CAPTURE_CAT_TO_DISPLAY_FAMILIES[cat] || [];
  const out = [];
  for (const f of fams) {
    for (const n of DISPLAY_PRESET_CATEGORIES[f] || []) {
      if (n !== "Direct / No Display" && !out.includes(n)) out.push(n);
    }
  }
  return out.slice(0, limit);
}
